name: Build And Test Spring Boot App
on:
  push:
    branches:
      - 'master'

jobs:
  vpush:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: ./.github/actions/if-action
        with:
          run-tests: false
