name: Build And Test Spring Boot App
on:
  push:
    branches:
      - 'master'

jobs:
  vpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run if-actino
        uses: ./.github/actions/if-action
        with:
          run-tests: false
